-- 코드를 입력하세요
SELECT T1.PRODUCT_CODE, (T1.PRICE * SUM(T2.SALES_AMOUNT)) as SALES
FROM PRODUCT T1, OFFLINE_SALE T2
WHERE T1.PRODUCT_ID = T2.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE
-- 코드를 입력하세요
# SELECT T1.PRODUCT_CODE, T1.PRICE, T2.SALES_AMOUNT
# FROM PRODUCT T1, OFFLINE_SALE T2
# WHERE T1.PRODUCT_ID = T2.PRODUCT_ID